In [ ]:
# 20 เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมา
# ทำเป็น matrix

# 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [3]:
import numpy as np
def makeInput(cache):
    def validateInput(index):
        while True:
            val = int(input('ให้ป้อนเลข {} '.format(index)))
            if val < 10 or val > 100:
                print('เลขต้องมีค่าอยู่ในช่วง 10-100')
                continue
            elif val in cache:
                print('ตัวต้องไม่ซ้ำกัน')
                continue
            else:
                cache.append(val)
                break
        return cache
    return validateInput

lst = []
vInput = makeInput(lst)
for i in range(9):
    lst = vInput(i+1)
mat = np.array(lst).reshape(3,3)
print(mat)
print('transpose')
t = mat.T
print(t)
print('เลขอยู่ตำแหน่งที่ (2,2)')
print(t[2,2])
    

ให้ป้อนเลข 1 10
ให้ป้อนเลข 2 20
ให้ป้อนเลข 3 30
ให้ป้อนเลข 4 40
ให้ป้อนเลข 5 50
ให้ป้อนเลข 6 60
ให้ป้อนเลข 7 70
ให้ป้อนเลข 8 80
ให้ป้อนเลข 9 0
เลขต้องมีค่าอยู่ในช่วง 10-100
ให้ป้อนเลข 9 1010
เลขต้องมีค่าอยู่ในช่วง 10-100
ให้ป้อนเลข 9 80
ตัวต้องไม่ซ้ำกัน
ให้ป้อนเลข 9 10
ตัวต้องไม่ซ้ำกัน
ให้ป้อนเลข 9 100
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 100]]
transpose
[[ 10  40  70]
 [ 20  50  80]
 [ 30  60 100]]
เลขอยู่ตำแหน่งที่ (2,2)
100
